apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-server-deployment
  namespace: go-http-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-http-server
  template:
    metadata:
      labels:
        app: go-http-server
    spec:
      containers:
        - name: go-http-server
          image: go-http-server:latest
          imagePullPolicy: Never # Pull images only from local - Delete this parameter to obtain always the image from dockerhub
          resources:
            limits:
              memory: '512Mi'
              cpu: '500m'
          ports:
            - containerPort: 8080
