apiVersion: v1
kind: Service
metadata:
  name: go-http-server-service
  namespace: go-http-server
spec:
  selector:
    app: go-http-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
  type: LoadBalancer
