# CI-CD workflow for Golang App and Docker Hub
name: CI-CD

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths-ignore:
      - .github/**
      - docs/**
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.22']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Git Sumbodule Update
        run: |
          git submodule update --remote --recursive

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Tidy
        run: go mod tidy

      - name: Run tests
        run: go test -race ./...

  push_to_registry:
    name: Push Docker image to Docker Hub

    runs-on: ubuntu-latest

    # build docker image and push to docker hub
    # only if the app build and test successfully
    needs: [build_test]

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: antoniomarfer/go-http-server

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./build/package/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
